var java = {
  primary: misc.or(                           "primaryNoNewArray"),
  primaryNoNewArray: misc.or(                 "classInstanceCreationExpression",
                                              "methodInvocation",
                                              "fieldAccess",
                                              "arrayAccess",
                                              "identifier",
                                              "this"),
  this: misc.dumbTerminal("this"),
  classInstanceCreationExpression: misc.sAlt( ["new ", "classOrInterfaceType", "()"],
                                              ["primary", ".", "new ", "identifier", "()"],
  "array-access"),
  methodInvocation: misc.sAlt(                ["primary", ".", "methodName", "()"],
                                              ["methodName", "()"],
  "method-invocation"),
  fieldAccess: misc.sAlt(                     ["primary", ".", "identifier"],
                                              ["super", ".", "identifier"],
  "field-access"),
  super: misc.dumbTerminal("super"),
  arrayAccess: misc.sAlt(                     ["primary", "[", "expression", "]"],
                                              ["expressionName", "[", "expression", "]"],
  "array-access"),
  classOrInterfaceType: misc.or(              "className", "interfaceTypeName"),
  className: misc.dumbTerminal(               new RegExp("C|D", "yg")),
  interfaceTypeName: misc.dumbTerminal(       new RegExp("I|J", "yg")),
  identifier: misc.or(                        "xOrY", "classOrInterfaceType"),
  xOrY: misc.dumbTerminal(                    new RegExp("x|y", "yg")),
  methodName: misc.dumbTerminal(              new RegExp("m|n", "yg")),
  expressionName: misc.or(                    "identifier"),
  expression: misc.dumbTerminal(              new RegExp("i|j", "yg")),
};
